# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('share_house', '0002_auto_20161223_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_title', models.CharField(max_length=20)),
                ('meet_catagory', models.CharField(max_length=20)),
                ('meet_time_start', models.DateTimeField()),
                ('meet_time_end', models.DateTimeField()),
                ('meet_dur_start', models.DateTimeField()),
                ('meet_dur_end', models.DateTimeField()),
                ('meet_place', models.CharField(max_length=100)),
                ('meet_comment', models.TextField()),
            ],
        ),
    ]
